name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: animated-surfer-471108-i9      # 👉 replace with your project ID
  GAR_NAME : gh-demo
  REGION: us-central1          # 👉 choose your region
  REPO: my-repo                # 👉 Artifact Registry repo name
  SERVICE: myapp          # 👉 Cloud Run service name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.TEST_SECRET }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker image
        run: |
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Show deployed URL
        run: echo "App deployed at ${{ steps.deploy.outputs.url }}"
